version: '3'
services:
    app:
        build: .
        tty: true
        ports:
            - 8080:8080
        volumes:
            - ../:/app
        depends_on:
            - db
    db:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: railsdb
            MYSQL_USER: okarin
            MYSQL_PASSWORD: okarin
            MYSQL_ROOT_PASSWORD: okarin
            TZ: 'Asia/Tokyo'